// Code generated by MockGen. DO NOT EDIT.
// Source: gostub/log (interfaces: ILogger)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/logger.go -package=mocks . ILogger
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	log "github.com/Rom4eg/gostub/log"

	gomock "go.uber.org/mock/gomock"
)

// MockILogger is a mock of ILogger interface.
type MockILogger struct {
	ctrl     *gomock.Controller
	recorder *MockILoggerMockRecorder
	isgomock struct{}
}

// MockILoggerMockRecorder is the mock recorder for MockILogger.
type MockILoggerMockRecorder struct {
	mock *MockILogger
}

// NewMockILogger creates a new mock instance.
func NewMockILogger(ctrl *gomock.Controller) *MockILogger {
	mock := &MockILogger{ctrl: ctrl}
	mock.recorder = &MockILoggerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockILogger) EXPECT() *MockILoggerMockRecorder {
	return m.recorder
}

// Debug mocks base method.
func (m *MockILogger) Debug(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Debug", msg)
}

// Debug indicates an expected call of Debug.
func (mr *MockILoggerMockRecorder) Debug(msg any) *MockILoggerDebugCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Debug", reflect.TypeOf((*MockILogger)(nil).Debug), msg)
	return &MockILoggerDebugCall{Call: call}
}

// MockILoggerDebugCall wrap *gomock.Call
type MockILoggerDebugCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILoggerDebugCall) Return() *MockILoggerDebugCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILoggerDebugCall) Do(f func(string)) *MockILoggerDebugCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILoggerDebugCall) DoAndReturn(f func(string)) *MockILoggerDebugCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Error mocks base method.
func (m *MockILogger) Error(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Error", msg)
}

// Error indicates an expected call of Error.
func (mr *MockILoggerMockRecorder) Error(msg any) *MockILoggerErrorCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Error", reflect.TypeOf((*MockILogger)(nil).Error), msg)
	return &MockILoggerErrorCall{Call: call}
}

// MockILoggerErrorCall wrap *gomock.Call
type MockILoggerErrorCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILoggerErrorCall) Return() *MockILoggerErrorCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILoggerErrorCall) Do(f func(string)) *MockILoggerErrorCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILoggerErrorCall) DoAndReturn(f func(string)) *MockILoggerErrorCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Info mocks base method.
func (m *MockILogger) Info(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Info", msg)
}

// Info indicates an expected call of Info.
func (mr *MockILoggerMockRecorder) Info(msg any) *MockILoggerInfoCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Info", reflect.TypeOf((*MockILogger)(nil).Info), msg)
	return &MockILoggerInfoCall{Call: call}
}

// MockILoggerInfoCall wrap *gomock.Call
type MockILoggerInfoCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILoggerInfoCall) Return() *MockILoggerInfoCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILoggerInfoCall) Do(f func(string)) *MockILoggerInfoCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILoggerInfoCall) DoAndReturn(f func(string)) *MockILoggerInfoCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Print mocks base method.
func (m *MockILogger) Print(arg0 *log.Log) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Print", arg0)
}

// Print indicates an expected call of Print.
func (mr *MockILoggerMockRecorder) Print(arg0 any) *MockILoggerPrintCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Print", reflect.TypeOf((*MockILogger)(nil).Print), arg0)
	return &MockILoggerPrintCall{Call: call}
}

// MockILoggerPrintCall wrap *gomock.Call
type MockILoggerPrintCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILoggerPrintCall) Return() *MockILoggerPrintCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILoggerPrintCall) Do(f func(*log.Log)) *MockILoggerPrintCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILoggerPrintCall) DoAndReturn(f func(*log.Log)) *MockILoggerPrintCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Warning mocks base method.
func (m *MockILogger) Warning(msg string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Warning", msg)
}

// Warning indicates an expected call of Warning.
func (mr *MockILoggerMockRecorder) Warning(msg any) *MockILoggerWarningCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Warning", reflect.TypeOf((*MockILogger)(nil).Warning), msg)
	return &MockILoggerWarningCall{Call: call}
}

// MockILoggerWarningCall wrap *gomock.Call
type MockILoggerWarningCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockILoggerWarningCall) Return() *MockILoggerWarningCall {
	c.Call = c.Call.Return()
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockILoggerWarningCall) Do(f func(string)) *MockILoggerWarningCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockILoggerWarningCall) DoAndReturn(f func(string)) *MockILoggerWarningCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
