// Code generated by MockGen. DO NOT EDIT.
// Source: gostub/internal/service/http (interfaces: IServer)
//
// Generated by this command:
//
//	mockgen -typed -destination=mocks/server.go -package=mocks . IServer
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockIServer is a mock of IServer interface.
type MockIServer struct {
	ctrl     *gomock.Controller
	recorder *MockIServerMockRecorder
	isgomock struct{}
}

// MockIServerMockRecorder is the mock recorder for MockIServer.
type MockIServerMockRecorder struct {
	mock *MockIServer
}

// NewMockIServer creates a new mock instance.
func NewMockIServer(ctrl *gomock.Controller) *MockIServer {
	mock := &MockIServer{ctrl: ctrl}
	mock.recorder = &MockIServerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIServer) EXPECT() *MockIServerMockRecorder {
	return m.recorder
}

// ListenAndServe mocks base method.
func (m *MockIServer) ListenAndServe() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListenAndServe")
	ret0, _ := ret[0].(error)
	return ret0
}

// ListenAndServe indicates an expected call of ListenAndServe.
func (mr *MockIServerMockRecorder) ListenAndServe() *MockIServerListenAndServeCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListenAndServe", reflect.TypeOf((*MockIServer)(nil).ListenAndServe))
	return &MockIServerListenAndServeCall{Call: call}
}

// MockIServerListenAndServeCall wrap *gomock.Call
type MockIServerListenAndServeCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServerListenAndServeCall) Return(arg0 error) *MockIServerListenAndServeCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServerListenAndServeCall) Do(f func() error) *MockIServerListenAndServeCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServerListenAndServeCall) DoAndReturn(f func() error) *MockIServerListenAndServeCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Shutdown mocks base method.
func (m *MockIServer) Shutdown(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Shutdown", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Shutdown indicates an expected call of Shutdown.
func (mr *MockIServerMockRecorder) Shutdown(ctx any) *MockIServerShutdownCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Shutdown", reflect.TypeOf((*MockIServer)(nil).Shutdown), ctx)
	return &MockIServerShutdownCall{Call: call}
}

// MockIServerShutdownCall wrap *gomock.Call
type MockIServerShutdownCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockIServerShutdownCall) Return(arg0 error) *MockIServerShutdownCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockIServerShutdownCall) Do(f func(context.Context) error) *MockIServerShutdownCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockIServerShutdownCall) DoAndReturn(f func(context.Context) error) *MockIServerShutdownCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
